name: Console

on:
  schedule:
    - cron: '0 0 */4 * *'
  workflow_dispatch:
    inputs:
      action_type:
        description: 操作类型
        required: true
        default: show
        type: choice
        options:
          - test
          - task
          - show
          - restart
      tag_name:
        description: Server Tag (仅用于 show 或 restart)
        required: false
        type: string
        default: all

jobs:
  run:
    permissions:
      contents: write
    strategy:
      fail-fast: true
      matrix:
        os:
          - ubuntu-latest
    runs-on: ${{ matrix.os }}

    container:
      image: cloakhq/cloakbrowser

    steps:
      - name: Determine PARAM
        run: |
          if [ "${{ github.event_name }}" == "schedule" ]; then
            echo "PARAM=show" >> $GITHUB_ENV
          else
            echo "PARAM=${{ github.event.inputs.action_type }}" >> $GITHUB_ENV
          fi

      - uses: actions/checkout@v6
        with:
          token: ${{ secrets.SOURCE_REPO_PAT }}
          repository: HEUDavid/AutoAction
          ref: main

      - name: Run
        run: ./tools/cicd.sh
        env:
          ZIP_PASSWORD: ${{ secrets.ZIP_PASSWORD }}
          DEBIAN_FRONTEND: noninteractive
        shell: bash

      - uses: softprops/action-gh-release@v3
        with:
          name: Latest
          tag_name: latest
          files: data.zip