name: Run Task On Windows

on:
  push:
    branches: [ main ]

jobs:
  run:
    permissions:
      contents: write
    strategy:
      fail-fast: true
      matrix:
        os:
          - windows-latest
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v6
        with:
          token: ${{ secrets.SOURCE_REPO_PAT }}
          repository: HEUDavid/AutoAction
          ref: main

      - uses: actions/setup-python@v6
        with:
          python-version: 3.12
          cache: pip
          pip-install: requirements.txt

      - name: Run
        run: .\tools\cicd_windows.ps1
        env:
          ZIP_PASSWORD: ${{ secrets.ZIP_PASSWORD }}
        shell: pwsh

      - uses: softprops/action-gh-release@v3
        with:
          name: Latest
          tag_name: latest
          files: data.zip